package com.be.mobilepush;

import com.be.enrollment.repository.EnrollmentRepository;
import com.be.notification.NotificationCreated;
import com.be.notification.enums.NotificationType;
import com.be.notification.service.NotificationService;
import com.be.push.*;
import com.be.security.JwtTestSupport;
import java.io.IOException;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.annotation.*;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.springframework.test.context.*;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.transaction.*;
import org.springframework.transaction.annotation.*;
import org.springframework.transaction.support.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;
import static com.be.mobilepush.MobilePushTestSupport.*;

@DataJpaTest(showSql = false, properties = {"spring.jpa.hibernate.ddl-auto=none", "spring.sql.init.mode=never"})
@Import({MobilePushIntegrationTest.Config.class, NotificationService.class, MobilePushSubscriptionService.class,
        MobilePushDeliveryStore.class, MobilePushDispatcher.class, ExpoPushReceiptPoller.class, PushDispatcher.class, PushDeliveryStore.class})
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class MobilePushIntegrationTest {
    static final String INSTALL = "11111111-1111-1111-1111-111111111111";
    @org.springframework.boot.test.context.TestConfiguration(proxyBeanMethods = false)
    static class Config {
        @Bean MutableClock clock() { return new MutableClock(); }
        @Bean MobilePushProperties mobileProperties() { return ENABLED; }
        @Bean MobilePushTasks mobileTasks() { return new MobilePushTasks(new Tasks()); }
        @Bean Tasks webTasks() { return new Tasks(); }
        @Bean PushProperties webProperties() { return new PushProperties(true, null, null, null); }
    }
    @Autowired MobilePushSubscriptionService service;
    @Autowired MobilePushSubscriptionRepository repository;
    @Autowired MobilePushDeliveryStore store;
    @Autowired MobilePushTasks mobileTasks;
    @Autowired Tasks webTasks;
    @Autowired MutableClock clock;
    @Autowired ExpoPushReceiptPoller poller;
    @Autowired JdbcTemplate jdbc;
    @Autowired PlatformTransactionManager transactions;
    @Autowired NotificationService notifications;
    @Autowired EnrollmentRepository enrollments;
    @Autowired ApplicationEventPublisher events;
    @MockitoBean ExpoPushTransport expo;
    @MockitoBean PushTransport web;
    Tasks tasks() { return (Tasks) org.springframework.test.util.ReflectionTestUtils.getField(mobileTasks, "delegate"); }
    @DynamicPropertySource static void properties(DynamicPropertyRegistry r) {
        r.add("jwt.secret", JwtTestSupport::secret); r.add("jwt.access-token-ttl-seconds", () -> 300); r.add("jwt.refresh-token-ttl-seconds", () -> 3600);
    }
    @BeforeEach void setup() throws Exception {
        tasks().reset(); webTasks.reset();
        ((Map<?, ?>) org.springframework.test.util.ReflectionTestUtils.getField(poller, "pending")).clear();
        new ResourceDatabasePopulator(new ClassPathResource("push-schema.sql")).execute(Objects.requireNonNull(jdbc.getDataSource()));
        jdbc.execute("CREATE TABLE member_roles(member_id BIGINT, role VARCHAR(20))");
        jdbc.execute("INSERT INTO member_roles VALUES(2,'EMPLOYEE'),(3,'EMPLOYEE')");
        // Inline test fixture only; production schema remains exclusively docs/LearnFlow.sql.
        jdbc.execute("""
            CREATE TABLE mobile_push_subscriptions(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            member_id BIGINT NOT NULL REFERENCES members(id), installation_id VARCHAR(36) NOT NULL UNIQUE,
            installation_secret_hash VARCHAR(64) NOT NULL, expo_push_token VARCHAR(512), token_hash VARCHAR(64) UNIQUE,
            platform VARCHAR(10) NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE NOT NULL, binding_generation BIGINT NOT NULL DEFAULT 0, version BIGINT NOT NULL DEFAULT 0)
            """);
        when(expo.send(any(), any())).thenReturn(new ExpoPushTransport.Result(200, "ticket", null, null));
        when(web.send(any(), any())).thenReturn(new PushTransport.Result(201, null));
    }
    @AfterEach void cleanup() {
        jdbc.execute("DROP TABLE mobile_push_subscriptions"); jdbc.execute("DROP TABLE member_roles");
        jdbc.execute("DROP TABLE push_subscriptions"); jdbc.execute("DROP TABLE notifications"); jdbc.execute("DROP TABLE enrollments");
        jdbc.execute("DROP TABLE members"); jdbc.execute("DROP TABLE courses"); jdbc.execute("DROP TABLE assignment_rules");
    }
    MobilePushDtos.Response bind() { return service.bind(2L, SECRET, binding(INSTALL, 1)); }
    MobilePushDtos.Response active() { var s = bind(); return service.register(2L, s.subscriptionId(), SECRET, token("device", s.version())); }
    void business(boolean rollback) {
        new TransactionTemplate(transactions).executeWithoutResult(tx -> {
            var e = enrollments.findById(3L).orElseThrow(); e.completeLearning(LocalDateTime.of(2026, 10, 4, 0, 0));
            notifications.notify(e, NotificationType.COURSE_COMPLETED);
            assertThat(tasks().immediate).isEmpty(); assertThat(webTasks.immediate).isEmpty();
            if (rollback) tx.setRollbackOnly();
        });
    }
    @Test void bindingIsIdempotentAndAllowsMultipleInstallations() {
        var first = bind(); var repeated = bind();
        assertThat(repeated).isEqualTo(first); assertThat(first.enabled()).isFalse();
        assertThat(service.bind(2L, SECRET, binding("22222222-2222-2222-2222-222222222222", 1)).subscriptionId()).isNotEqualTo(first.subscriptionId());
        assertThat(repository.count()).isEqualTo(2);
    }
    @Test void transferDisablesAndRejectsWrongSecretOldVersionsAndPreviousOwner() {
        var s = active();
        assertThatThrownBy(() -> service.bind(3L, "x".repeat(43), binding(INSTALL, 2))).isInstanceOf(com.be.global.exception.BusinessException.class);
        var moved = service.bind(3L, SECRET, binding(INSTALL, 2));
        assertThat(moved.enabled()).isFalse(); assertThat(moved.version()).isGreaterThan(s.version());
        assertThat(service.bind(3L, SECRET, binding(INSTALL, 2))).isEqualTo(moved);
        assertThatThrownBy(() -> service.bind(2L, SECRET, binding(INSTALL, 1))).isInstanceOf(com.be.global.exception.BusinessException.class);
        assertThatThrownBy(() -> service.get(2L, s.subscriptionId())).isInstanceOf(com.be.global.exception.BusinessException.class);
        assertThatThrownBy(() -> service.disable(2L, s.subscriptionId(), SECRET, s.version())).isInstanceOf(com.be.global.exception.BusinessException.class);
    }
    @Test void tokenUpdateDuplicateAndRepeatedDisable() {
        var s = active();
        assertThat(service.register(2L, s.subscriptionId(), SECRET, token("device", s.version()))).isEqualTo(s);
        var updated = service.register(2L, s.subscriptionId(), SECRET, token("new", s.version()));
        assertThat(updated.version()).isGreaterThan(s.version());
        var other = service.bind(3L, SECRET, binding("22222222-2222-2222-2222-222222222222", 1));
        assertThatThrownBy(() -> service.register(3L, other.subscriptionId(), SECRET, token("new", other.version()))).isInstanceOf(com.be.global.exception.BusinessException.class);
        assertThatThrownBy(() -> service.register(2L, s.subscriptionId(), SECRET, token("stale", s.version()))).isInstanceOf(com.be.global.exception.BusinessException.class);
        service.disable(2L, s.subscriptionId(), SECRET, updated.version());
        var disabled = service.get(2L, s.subscriptionId());
        service.disable(2L, s.subscriptionId(), SECRET, disabled.version());
        assertThat(service.get(2L, s.subscriptionId())).isEqualTo(disabled);
    }
    @Test void lostResponsesRecoverByGenerationWithoutKnowingServerVersion() {
        var original = active();
        // The caller discards the committed response, retaining its old version.
        service.bind(2L, SECRET, binding(INSTALL, 2));
        var recoveredA = service.bind(2L, SECRET, binding(INSTALL, 2));
        assertThat(recoveredA.enabled()).isFalse();
        assertThat(recoveredA.version()).isGreaterThan(original.version());
        service.bind(3L, SECRET, binding(INSTALL, 3)); // B also loses the response.
        var recoveredB = service.bind(3L, SECRET, binding(INSTALL, 3));
        assertThat(service.bind(3L, SECRET, binding(INSTALL, 3))).isEqualTo(recoveredB);
        assertThat(recoveredB.enabled()).isFalse();
        assertThatThrownBy(() -> service.bind(2L, SECRET, binding(INSTALL, 2)))
                .isInstanceOf(com.be.global.exception.BusinessException.class);
        assertThatThrownBy(() -> service.bind(2L, SECRET, binding(INSTALL, 3)))
                .isInstanceOf(com.be.global.exception.BusinessException.class);
        assertThatThrownBy(() -> service.bind(3L, "x".repeat(43), binding(INSTALL, 3)))
                .isInstanceOf(com.be.global.exception.BusinessException.class);
        var on = service.register(3L, recoveredB.subscriptionId(), SECRET, token("recovered", recoveredB.version()));
        assertThat(on.enabled()).isTrue();
        assertThat(service.bind(3L, SECRET, binding(INSTALL, 3))).isEqualTo(on);
        assertThatThrownBy(() -> service.register(2L, original.subscriptionId(), SECRET, token("late", original.version())))
                .isInstanceOf(com.be.global.exception.BusinessException.class);
        assertThatThrownBy(() -> service.disable(2L, original.subscriptionId(), SECRET, original.version()))
                .isInstanceOf(com.be.global.exception.BusinessException.class);
        store.disable(original.subscriptionId(), original.version());
        assertThat(service.get(3L, original.subscriptionId()).enabled()).isTrue();
    }
    @Test void concurrentGenerationsCannotRevertNewOwner() throws Exception {
        active();
        try (var executor = java.util.concurrent.Executors.newFixedThreadPool(2)) {
            var start = new java.util.concurrent.CountDownLatch(1);
            var older = executor.submit(() -> {
                start.await();
                try { service.bind(2L, SECRET, binding(INSTALL, 2)); }
                catch (com.be.global.exception.BusinessException expected) {
                    assertThat(expected.getErrorCode()).isEqualTo(com.be.global.exception.ErrorCode.MOBILE_PUSH_CONFLICT);
                }
                return true;
            });
            var newer = executor.submit(() -> { start.await(); return service.bind(3L, SECRET, binding(INSTALL, 3)); });
            start.countDown(); older.get(10, java.util.concurrent.TimeUnit.SECONDS);
            var result = newer.get(10, java.util.concurrent.TimeUnit.SECONDS);
            assertThat(service.get(3L, result.subscriptionId()).enabled()).isFalse();
            assertThat(jdbc.queryForObject("SELECT binding_generation FROM mobile_push_subscriptions", Long.class)).isEqualTo(3);
        }
    }
    @Test void committedEventDispatchesBothOutsideTransaction() throws Exception {
        active(); webSubscription();
        when(expo.send(any(), any())).thenAnswer(c -> { assertThat(TransactionSynchronizationManager.isActualTransactionActive()).isFalse(); return new ExpoPushTransport.Result(200, "ticket", null, null); });
        business(false); assertThat(tasks().immediate).hasSize(1); assertThat(webTasks.immediate).hasSize(1);
        tasks().run(); webTasks.run(); verify(expo).send(any(), any()); verify(web).send(any(), any());
        assertThat(jdbc.queryForObject("SELECT read_at FROM notifications", Object.class)).isNull();
    }
    @Test void rollbackAndNontransactionalEventDoNotSend() throws Exception {
        active(); business(true); events.publishEvent(new NotificationCreated(10L));
        assertThat(tasks().immediate).isEmpty(); assertThat(webTasks.immediate).isEmpty(); verifyNoInteractions(expo, web);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM notifications", Long.class)).isZero();
    }
    @Test void expoNetworkFailureDoesNotUndoBusinessOrBlockWeb() throws Exception {
        active(); webSubscription(); when(expo.send(any(), any())).thenThrow(new IOException("sensitive upstream error"));
        business(false); tasks().run(); tasks().retryAll(); webTasks.run();
        verify(expo, times(3)).send(any(), any()); verify(web).send(any(), any()); preserved();
    }
    @Test void expoQueueSaturationDoesNotBlockWebOrCommit() throws Exception {
        active(); webSubscription(); tasks().accept = false; business(false); webTasks.run();
        verifyNoInteractions(expo); verify(web).send(any(), any()); preserved();
    }
    @Test void staleDeliveryAndReceiptCannotAffectNewOwnerOrToken() {
        var s = active(); business(false);
        Long n = jdbc.queryForObject("SELECT id FROM notifications", Long.class);
        var ref = store.targets(n).getFirst();
        var moved = service.bind(3L, SECRET, binding(INSTALL, 2));
        var current = service.register(3L, s.subscriptionId(), SECRET, token("replacement", moved.version()));
        assertThat(store.load(n, ref)).isEmpty(); store.disable(ref.id(), ref.version());
        assertThat(service.get(3L, s.subscriptionId()).enabled()).isTrue();
        store.disable(current.subscriptionId(), current.version()); assertThat(service.get(3L, s.subscriptionId()).enabled()).isFalse();
    }
    @Test void staleErrorCannotDisableRotatedTokenForSameMember() {
        var s = active(); business(false);
        Long n = jdbc.queryForObject("SELECT id FROM notifications", Long.class);
        var ref = store.targets(n).getFirst();
        var updated = service.register(2L, s.subscriptionId(), SECRET, token("rotated", s.version()));
        assertThat(store.load(n, ref)).isEmpty(); store.disable(ref.id(), ref.version());
        assertThat(service.get(2L, s.subscriptionId()).enabled()).isTrue();
        assertThat(updated.version()).isGreaterThan(ref.version());
    }
    @Test void concurrentFirstBindingForSameMemberCreatesOneRow() throws Exception {
        try (var executor = java.util.concurrent.Executors.newFixedThreadPool(2)) {
            var start = new java.util.concurrent.CountDownLatch(1);
            java.util.concurrent.Callable<Long> operation = () -> { start.await(); return bind().subscriptionId(); };
            var a = executor.submit(operation); var b = executor.submit(operation); start.countDown();
            assertThat(a.get(10, java.util.concurrent.TimeUnit.SECONDS)).isEqualTo(b.get(10, java.util.concurrent.TimeUnit.SECONDS));
            assertThat(repository.count()).isEqualTo(1);
        }
    }
    @Test void deviceNotRegisteredDisablesOnlyCurrentVersion() throws Exception {
        var s = active(); when(expo.send(any(), any())).thenReturn(new ExpoPushTransport.Result(200, null, "DeviceNotRegistered", null));
        business(false); tasks().run(); assertThat(service.get(2L, s.subscriptionId()).enabled()).isFalse(); preserved();
    }
    @Test void receiptUsesVersionGuardAcrossAccountTransfer() throws Exception {
        var s = active(); business(false); tasks().run();
        var moved = service.bind(3L, SECRET, binding(INSTALL, 2));
        service.register(3L, s.subscriptionId(), SECRET, token("new", moved.version()));
        when(expo.receipts(any())).thenReturn(new ExpoPushTransport.Receipts(200, Map.of("ticket", "DeviceNotRegistered"), null));
        clock.advance(901); poller.poll();
        assertThat(service.get(3L, s.subscriptionId()).enabled()).isTrue();
    }
    @Test void receiptFailureDoesNotBlockWeb() throws Exception {
        active(); webSubscription(); business(false); tasks().run();
        webTasks.run();
        when(expo.receipts(any())).thenThrow(new IOException()); clock.advance(901); poller.poll();
        new TransactionTemplate(transactions).executeWithoutResult(tx -> events.publishEvent(new NotificationCreated(1L)));
        webTasks.run(); verify(web, times(2)).send(any(), any()); preserved();
    }
    @Test void resignedAndNonEmployeeAreExcludedAtSendTime() throws Exception {
        active(); business(false); jdbc.update("DELETE FROM member_roles WHERE member_id=2"); tasks().run(); verifyNoInteractions(expo);
        jdbc.update("INSERT INTO member_roles VALUES(2,'EMPLOYEE')"); jdbc.update("UPDATE members SET status='RESIGNED' WHERE id=2");
        Long n = jdbc.queryForObject("SELECT id FROM notifications", Long.class); assertThat(store.targets(n)).isEmpty();
    }
    void preserved() {
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM notifications", Long.class)).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT status FROM enrollments WHERE id=3", String.class)).isEqualTo("COMPLETED");
    }
    void webSubscription() {
        jdbc.update("INSERT INTO push_subscriptions(member_id,endpoint,endpoint_hash,p256dh,auth,enabled,created_at,updated_at) VALUES(2,'https://fcm.googleapis.com/device','hash','key','auth',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
    }
}
