-- Isolated H2 integration fixture: production columns and PK/UNIQUE/FK, excluding MySQL-only CHECKs/indexes.
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    parent_department_id BIGINT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_departments_code
        UNIQUE (code),
    CONSTRAINT fk_departments_parent
        FOREIGN KEY (parent_department_id)
        REFERENCES departments (id)
        ON DELETE RESTRICT

);

CREATE TABLE job_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_job_positions_code
        UNIQUE (code)
);

CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    employee_number VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    department_id BIGINT NOT NULL,
    job_position_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    hire_date DATE NOT NULL,
    resigned_at TIMESTAMP(6) NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_members_employee_number
        UNIQUE (employee_number),
    CONSTRAINT uk_members_email
        UNIQUE (email),
    CONSTRAINT fk_members_department
        FOREIGN KEY (department_id)
        REFERENCES departments (id)
        ON DELETE RESTRICT
        ,
    CONSTRAINT fk_members_job_position
        FOREIGN KEY (job_position_id)
        REFERENCES job_positions (id)
        ON DELETE RESTRICT

);

CREATE TABLE member_roles (
    member_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    PRIMARY KEY (member_id, role),
    CONSTRAINT fk_member_roles_member
        FOREIGN KEY (member_id)
        REFERENCES members (id)
        ON DELETE RESTRICT

);

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title VARCHAR(200) NOT NULL,
    description TEXT NULL,
    course_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    start_date DATE NULL,
    end_date DATE NULL,
    passing_progress_rate DECIMAL(5,2) NOT NULL DEFAULT 100.00,
    instructor_id BIGINT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_courses_instructor
        FOREIGN KEY (instructor_id)
        REFERENCES members (id)
        ON DELETE RESTRICT

);

CREATE TABLE course_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    content_type VARCHAR(20) NOT NULL,
    content_url VARCHAR(2048) NOT NULL,
    duration_seconds INT NULL,
    sort_order INT NOT NULL,
    is_required BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_course_contents_course_sort_order
        UNIQUE (course_id, sort_order),
    CONSTRAINT fk_course_contents_course
        FOREIGN KEY (course_id)
        REFERENCES courses (id)
        ON DELETE RESTRICT

);

CREATE TABLE assignment_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id BIGINT NOT NULL,
    rule_type VARCHAR(30) NOT NULL,
    department_id BIGINT NULL,
    job_position_id BIGINT NULL,
    new_employee_days SMALLINT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_assignment_rules_course
        FOREIGN KEY (course_id)
        REFERENCES courses (id)
        ON DELETE RESTRICT
        ,
    CONSTRAINT fk_assignment_rules_department
        FOREIGN KEY (department_id)
        REFERENCES departments (id)
        ON DELETE RESTRICT
        ,
    CONSTRAINT fk_assignment_rules_job_position
        FOREIGN KEY (job_position_id)
        REFERENCES job_positions (id)
        ON DELETE RESTRICT

);

CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ASSIGNED',
    assignment_source VARCHAR(20) NOT NULL,
    assignment_rule_id BIGINT NULL,
    assigned_at TIMESTAMP(6) NOT NULL,
    started_at TIMESTAMP(6) NULL,
    completed_at TIMESTAMP(6) NULL,
    due_date DATE NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_enrollments_member_course
        UNIQUE (member_id, course_id),
    CONSTRAINT fk_enrollments_member
        FOREIGN KEY (member_id)
        REFERENCES members (id)
        ON DELETE RESTRICT
        ,
    CONSTRAINT fk_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES courses (id)
        ON DELETE RESTRICT
        ,
    CONSTRAINT fk_enrollments_assignment_rule
        FOREIGN KEY (assignment_rule_id)
        REFERENCES assignment_rules (id)
        ON DELETE RESTRICT

);

CREATE TABLE content_progresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    enrollment_id BIGINT NOT NULL,
    course_content_id BIGINT NOT NULL,
    progress_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    completed_at TIMESTAMP(6) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_content_progresses_enrollment_content
        UNIQUE (enrollment_id, course_content_id),
    CONSTRAINT fk_content_progresses_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES enrollments (id)
        ON DELETE RESTRICT
        ,
    CONSTRAINT fk_content_progresses_content
        FOREIGN KEY (course_content_id)
        REFERENCES course_contents (id)
        ON DELETE RESTRICT

);

CREATE TABLE exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    passing_score DECIMAL(5,2) NOT NULL,
    max_attempts INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_exams_course
        UNIQUE (course_id),
    CONSTRAINT fk_exams_course
        FOREIGN KEY (course_id)
        REFERENCES courses (id)
        ON DELETE RESTRICT

);

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    exam_id BIGINT NOT NULL,
    question_text TEXT NOT NULL,
    question_type VARCHAR(30) NOT NULL,
    score DECIMAL(7,2) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_questions_exam_sort_order
        UNIQUE (exam_id, sort_order),
    CONSTRAINT fk_questions_exam
        FOREIGN KEY (exam_id)
        REFERENCES exams (id)
        ON DELETE RESTRICT

);

CREATE TABLE question_choices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    question_id BIGINT NOT NULL,
    choice_text VARCHAR(1000) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_question_choices_question_sort_order
        UNIQUE (question_id, sort_order),
    CONSTRAINT fk_question_choices_question
        FOREIGN KEY (question_id)
        REFERENCES questions (id)
        ON DELETE RESTRICT

);

CREATE TABLE exam_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    exam_id BIGINT NOT NULL,
    enrollment_id BIGINT NOT NULL,
    attempt_number INT NOT NULL,
    score DECIMAL(5,2) NULL,
    passed BOOLEAN NULL,
    started_at TIMESTAMP(6) NOT NULL,
    submitted_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_exam_attempts_enrollment_exam_number
        UNIQUE (enrollment_id, exam_id, attempt_number),
    CONSTRAINT fk_exam_attempts_exam
        FOREIGN KEY (exam_id)
        REFERENCES exams (id)
        ON DELETE RESTRICT
        ,
    CONSTRAINT fk_exam_attempts_enrollment
        FOREIGN KEY (enrollment_id)
        REFERENCES enrollments (id)
        ON DELETE RESTRICT

);

CREATE TABLE exam_answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    exam_attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    is_correct BOOLEAN NULL,
    earned_score DECIMAL(7,2) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_exam_answers_attempt_question
        UNIQUE (exam_attempt_id, question_id),
    CONSTRAINT fk_exam_answers_attempt
        FOREIGN KEY (exam_attempt_id)
        REFERENCES exam_attempts (id)
        ON DELETE RESTRICT
        ,
    CONSTRAINT fk_exam_answers_question
        FOREIGN KEY (question_id)
        REFERENCES questions (id)
        ON DELETE RESTRICT

);

CREATE TABLE exam_answer_choices (
    exam_answer_id BIGINT NOT NULL,
    question_choice_id BIGINT NOT NULL,
    PRIMARY KEY (exam_answer_id, question_choice_id),
    CONSTRAINT fk_exam_answer_choices_answer
        FOREIGN KEY (exam_answer_id)
        REFERENCES exam_answers (id)
        ON DELETE RESTRICT
        ,
    CONSTRAINT fk_exam_answer_choices_question_choice
        FOREIGN KEY (question_choice_id)
        REFERENCES question_choices (id)
        ON DELETE RESTRICT

);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT NOT NULL,
    enrollment_id BIGINT NOT NULL,
    type VARCHAR(30) NOT NULL,
    title VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    read_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_notifications_enrollment_type UNIQUE (enrollment_id, type),
    CONSTRAINT fk_notifications_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE RESTRICT ,
    CONSTRAINT fk_notifications_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(id) ON DELETE RESTRICT
);

CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    course_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NULL,
    is_required BOOLEAN NOT NULL,
    due_date DATE NOT NULL,
    passing_score DECIMAL(5,2) NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_assignments_course_sort_order UNIQUE (course_id, sort_order),
    CONSTRAINT fk_assignments_course FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE RESTRICT
);

CREATE TABLE assignment_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    assignment_id BIGINT NOT NULL,
    enrollment_id BIGINT NOT NULL,
    submission_type VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    submitted_at TIMESTAMP(6) NOT NULL,
    submission_count INT NOT NULL,
    score DECIMAL(5,2) NULL,
    passed BOOLEAN NULL,
    feedback TEXT NULL,
    graded_at TIMESTAMP(6) NULL,
    graded_by_member_id BIGINT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_assignment_submissions_assignment_enrollment UNIQUE (assignment_id, enrollment_id),
    CONSTRAINT fk_submissions_assignment FOREIGN KEY (assignment_id) REFERENCES assignments(id) ON DELETE RESTRICT ,
    CONSTRAINT fk_submissions_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(id) ON DELETE RESTRICT ,
    CONSTRAINT fk_submissions_grader FOREIGN KEY (graded_by_member_id) REFERENCES members(id) ON DELETE RESTRICT
);

CREATE TABLE certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    enrollment_id BIGINT NOT NULL,
    certificate_number VARCHAR(64) NOT NULL,
    issued_at TIMESTAMP(6) NOT NULL,
    member_name VARCHAR(100) NOT NULL,
    course_title VARCHAR(200) NOT NULL,
    completed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_certificates_enrollment UNIQUE (enrollment_id),
    CONSTRAINT uk_certificates_number UNIQUE (certificate_number),
    CONSTRAINT fk_certificates_enrollment FOREIGN KEY (enrollment_id) REFERENCES enrollments(id) ON DELETE RESTRICT
);

CREATE TABLE retraining_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    source_course_id BIGINT NOT NULL,
    base_title VARCHAR(150) NOT NULL,
    enabled BOOLEAN NOT NULL,
    auto_create BOOLEAN NOT NULL,
    auto_open BOOLEAN NOT NULL,
    interval_months INT NOT NULL,
    first_start_date DATE NOT NULL,
    duration_days INT NOT NULL,
    generation_lead_days INT NOT NULL,
    next_occurrence_number INT NOT NULL,
    next_generation_date DATE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_retraining_source FOREIGN KEY (source_course_id) REFERENCES courses(id) ON DELETE RESTRICT
);

ALTER TABLE courses ADD retraining_policy_id BIGINT;
ALTER TABLE courses ADD occurrence_number INT;
ALTER TABLE courses ADD CONSTRAINT uk_courses_retraining_occurrence UNIQUE(retraining_policy_id, occurrence_number);
ALTER TABLE courses ADD CONSTRAINT fk_courses_retraining FOREIGN KEY(retraining_policy_id) REFERENCES retraining_policies(id);
