spring:
  application:
    name: BE

  datasource:
    url: ${app.datasource.url}
    username: ${app.datasource.username}
    password: ${app.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET}
  access-token-ttl-seconds: ${JWT_ACCESS_TOKEN_TTL_SECONDS}
  refresh-token-ttl-seconds: ${JWT_REFRESH_TOKEN_TTL_SECONDS}
