package com.be.global.exception;

// Service와 Entity에서 공통으로 사용하는 업무 오류
public enum ErrorCode {
    MOBILE_PUSH_NOT_FOUND("모바일 Push 구독을 찾을 수 없습니다."),
    MOBILE_PUSH_CONFLICT("구독이 변경되었거나 이미 사용 중입니다. 상태를 확인해주세요."),
    MOBILE_PUSH_FORBIDDEN("모바일 Push 구독에 접근할 수 없습니다."),
    INVALID_MOBILE_PUSH("모바일 Push 요청 형식이 올바르지 않습니다."),
    INVALID_STATISTICS_RANGE("조회 시작일과 종료일, 최대 366일 범위 및 필터 ID를 확인해주세요. 미래 날짜는 조회할 수 없습니다."),
    PUSH_SUBSCRIPTION_NOT_FOUND("Push 구독을 찾을 수 없습니다."),
    PUSH_SUBSCRIPTION_CONFLICT("구독을 등록할 수 없습니다. 브라우저에서 구독을 새로 생성해주세요."),
    PUSH_SUBSCRIPTION_LIMIT("활성 Push 구독은 회원당 최대 10개입니다."),
    INVALID_PUSH_SUBSCRIPTION("Push 구독 형식 또는 endpoint가 올바르지 않습니다."),
    PUSH_DISABLED("Push 알림이 비활성화되어 있습니다."),
    RETRAINING_POLICY_NOT_FOUND("재교육 정책을 찾을 수 없습니다."),
    INVALID_RETRAINING_SCHEDULE("재교육 일정 또는 제목 설정이 올바르지 않습니다."),
    INVALID_RETRAINING_OCCURRENCE("현재 다음 회차를 지정해야 합니다."),
    RETRAINING_SCHEDULE_LOCKED("회차 처리 후에는 원본 및 핵심 일정을 변경할 수 없습니다."),
    RETRAINING_DISABLED("중지된 재교육 정책입니다."),
    RETRAINING_OVERDUE("종료일 또는 필수 과제 마감이 지난 회차입니다. 건너뛰기를 검토해주세요."),
    RETRAINING_DRAFT_PENDING("이전 회차가 DRAFT이므로 자동 생성을 보류합니다."),
    RETRAINING_NOT_OVERDUE("아직 마감되지 않은 회차는 건너뛸 수 없습니다."),
    RETRAINING_SOURCE_INVALID("시작일이 있는 원본과 새 기간에 맞는 과제 구성이 필요합니다."),
    RETRAINING_ACTIVE_RULE_REQUIRED("자동 공개에는 활성 배정 규칙이 필요합니다."),
    CERTIFICATE_NOT_ELIGIBLE("수료일이 기록된 COMPLETED 수강에만 수료증을 발급할 수 있습니다."),
    CERTIFICATE_ACCESS_DENIED("해당 수강의 수료증에 접근할 수 없습니다."),
    CERTIFICATE_NOT_FOUND("발급된 수료증이 없습니다."),
    CERTIFICATE_PDF_GENERATION_FAILED("수료증 PDF를 생성하지 못했습니다. 잠시 후 다시 시도해주세요."),
    ASSIGNMENT_NOT_FOUND("해당 과정의 과제를 찾을 수 없습니다."),
    ASSIGNMENT_SUBMISSION_NOT_FOUND("과제 제출물을 찾을 수 없습니다."),
    ASSIGNMENT_ACCESS_DENIED("해당 과제에 접근할 수 없습니다."),
    ASSIGNMENT_CONFIGURATION_LOCKED("DRAFT 과정에서만 과제를 변경할 수 있습니다."),
    DUPLICATE_ASSIGNMENT_SORT_ORDER("이미 사용 중인 과제 순서입니다."),
    INVALID_ASSIGNMENT_ORDER("전체 과제 ID를 중복 없이 지정해야 합니다."),
    INVALID_ASSIGNMENT_DUE_DATE("과제 마감일은 과정 운영 기간 안에 있어야 합니다."),
    INVALID_ASSIGNMENT_CONTENT("제출 유형에 맞는 텍스트 또는 http/https URL이 필요합니다."),
    ASSIGNMENT_SUBMISSION_NOT_EDITABLE("종료된 수강에서는 과제를 제출할 수 없습니다."),
    ASSIGNMENT_ALREADY_PASSED("이미 통과한 과제는 재제출할 수 없습니다."),
    ASSIGNMENT_ALREADY_GRADED("확정된 채점은 수정할 수 없습니다."),
    ASSIGNMENT_DEADLINE_PASSED("과제 제출 마감일이 지났습니다."),
    ASSIGNMENT_ENROLLMENT_DEADLINE_PASSED("필수 과제 마감이 지난 과정은 배정할 수 없습니다."),
    DEPARTMENT_NOT_FOUND("부서를 찾을 수 없습니다."),
    JOB_POSITION_NOT_FOUND("직무를 찾을 수 없습니다."),
    MEMBER_NOT_FOUND("회원을 찾을 수 없습니다."),
    DUPLICATE_DEPARTMENT_CODE("이미 사용 중인 부서 코드입니다."),
    DUPLICATE_JOB_POSITION_CODE("이미 사용 중인 직무 코드입니다."),
    DUPLICATE_EMPLOYEE_NUMBER("이미 사용 중인 사번입니다."),
    DUPLICATE_EMAIL("이미 사용 중인 이메일입니다."),
    INACTIVE_DEPARTMENT("비활성 부서를 지정할 수 없습니다."),
    INACTIVE_JOB_POSITION("비활성 직무를 지정할 수 없습니다."),
    SELF_PARENT_DEPARTMENT("자기 자신을 상위 부서로 지정할 수 없습니다."),
    DEPARTMENT_CYCLE("부서 계층에 순환 참조가 발생합니다."),
    INVALID_MEMBER_STATUS_TRANSITION("허용되지 않은 회원 상태 전이입니다."),
    RESIGNED_MEMBER_UPDATE("퇴사자의 일반 정보는 수정할 수 없습니다."),
    REQUIRED_EMPLOYEE_ROLE("EMPLOYEE 역할은 제거할 수 없습니다."),
    COURSE_NOT_FOUND("교육과정을 찾을 수 없습니다."),
    COURSE_CONTENT_NOT_FOUND("해당 교육과정의 콘텐츠를 찾을 수 없습니다."),
    INVALID_COURSE_INSTRUCTOR("지정한 회원은 INSTRUCTOR 역할이 없습니다."),
    INVALID_COURSE_PERIOD("교육 시작일은 종료일보다 늦을 수 없습니다."),
    COURSE_DATES_REQUIRED("공개·종료 교육과정에는 시작일과 종료일이 필요합니다."),
    INVALID_COURSE_STATUS_TRANSITION("허용되지 않은 교육과정 상태 전이입니다."),
    DUPLICATE_CONTENT_SORT_ORDER("이미 사용 중인 콘텐츠 순서입니다."),
    INVALID_CONTENT_ORDER("현재 교육과정의 전체 콘텐츠 ID를 중복 없이 지정해야 합니다."),
    CONTENT_ORDER_LIMIT_EXCEEDED("콘텐츠 순서 값이 재정렬 가능한 범위를 초과했습니다."),
    ASSIGNMENT_RULE_NOT_FOUND("해당 교육과정의 배정 규칙을 찾을 수 없습니다."),
    INVALID_ASSIGNMENT_RULE_TARGET("배정 규칙 유형과 대상 조건이 일치하지 않습니다."),
    INVALID_NEW_EMPLOYEE_DAYS("신입 대상 기간은 1~32767일이어야 합니다."),
    ENROLLMENT_NOT_FOUND("교육 배정 내역을 찾을 수 없습니다."),
    DUPLICATE_ENROLLMENT("이미 해당 직원에게 배정된 교육과정입니다."),
    COURSE_NOT_OPEN_FOR_ASSIGNMENT("OPEN 교육과정에만 신규 배정할 수 있습니다."),
    RESIGNED_MEMBER_ASSIGNMENT("퇴사자에게 신규 교육을 배정할 수 없습니다."),
    ENROLLMENT_PROGRESS_ACCESS_DENIED("해당 수강의 학습 진도에 접근할 수 없습니다."),
    ENROLLMENT_PROGRESS_NOT_EDITABLE("종료된 수강의 학습 진도는 변경할 수 없습니다."),
    INVALID_PROGRESS_RATE("진도율은 소수점 둘째 자리까지의 0~100 값이어야 합니다."),
    NOTIFICATION_NOT_FOUND("알림을 찾을 수 없습니다."),
    EXAM_NOT_FOUND("해당 과정의 시험을 찾을 수 없습니다."),
    DUPLICATE_EXAM("과정에는 시험을 하나만 생성할 수 있습니다."),
    QUESTION_NOT_FOUND("해당 시험의 문항을 찾을 수 없습니다."),
    QUESTION_CHOICE_NOT_FOUND("해당 문항의 선택지를 찾을 수 없습니다."),
    INVALID_EXAM_CONFIGURATION("응시 가능한 시험 구성이 아닙니다."),
    INVALID_QUESTION_CONFIGURATION("문제 유형에 맞는 선택지와 정답 구성이 필요합니다."),
    DUPLICATE_QUESTION_SORT_ORDER("이미 사용 중인 문항 순서입니다."),
    DUPLICATE_CHOICE_SORT_ORDER("이미 사용 중인 선택지 순서입니다."),
    INVALID_QUESTION_ORDER("시험의 전체 문항 ID를 중복 없이 지정해야 합니다."),
    INVALID_CHOICE_ORDER("문항의 전체 선택지 ID를 중복 없이 지정해야 합니다."),
    EXAM_ORDER_LIMIT_EXCEEDED("순서 값이 재정렬 가능한 범위를 초과했습니다."),
    EXAM_HISTORY_DELETE_CONFLICT("응시 또는 답안 이력이 있는 문항과 선택지는 삭제할 수 없습니다."),
    EXAM_CONFIGURATION_LOCKED("응시가 시작된 시험의 구성은 변경할 수 없습니다."),
    EXAM_ATTEMPT_NOT_FOUND("시험 응시 내역을 찾을 수 없습니다."),
    EXAM_ACCESS_DENIED("해당 시험 응시에 접근할 수 없습니다."),
    ENROLLMENT_EXAM_NOT_EDITABLE("종료된 수강에서는 시험 활동을 할 수 없습니다."),
    EXAM_ALREADY_PASSED("이미 합격한 시험입니다."),
    EXAM_ATTEMPTS_EXHAUSTED("시험 응시 횟수를 모두 사용했습니다."),
    INVALID_EXAM_ANSWER("문제 소속과 유형에 맞는 선택지를 중복 없이 지정해주세요."),
    EXAM_ATTEMPT_ALREADY_SUBMITTED("이미 제출된 시험입니다."),
    EXAM_ATTEMPT_NOT_SUBMITTED("아직 제출되지 않은 시험입니다.");

    private final String message;

    ErrorCode(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }
}
