package com.be.coursework;

import com.be.coursework.entity.*;
import com.be.coursework.enums.AssignmentSubmissionType;
import com.be.coursework.repository.*;
import com.be.enrollment.entity.Enrollment;
import jakarta.persistence.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import com.be.security.JwtTestSupport;
import static com.be.coursework.CourseworkFixtures.*;
import static org.assertj.core.api.Assertions.*;

@DataJpaTest(properties = {"spring.jpa.hibernate.ddl-auto=none",
    "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect",
    "spring.jpa.show-sql=false", "spring.sql.init.mode=never"})
class CourseworkRepositoryTest {
    @Autowired AssignmentRepository assignments;
    @Autowired AssignmentSubmissionRepository submissions;
    @Autowired JdbcTemplate jdbc;
    @Autowired EntityManagerFactory emf;
    @DynamicPropertySource static void properties(DynamicPropertyRegistry registry) {
        registry.add("jwt.secret",JwtTestSupport::secret);
        registry.add("jwt.access-token-ttl-seconds",()->300);
        registry.add("jwt.refresh-token-ttl-seconds",()->3600);
    }
    @BeforeEach void schema() {
        // 독립 인메모리 DB: 실제 JPQL 결과/UNIQUE/@Version을 검증하며 운영 DB에 연결하지 않는다.
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS assignments (
                id BIGINT PRIMARY KEY, course_id BIGINT NOT NULL, title VARCHAR(200) NOT NULL,
                description VARCHAR(10000), is_required BOOLEAN NOT NULL, due_date DATE NOT NULL,
                passing_score DECIMAL(5,2) NOT NULL, sort_order INT NOT NULL,
                created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL)
            """);
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS assignment_submissions (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                assignment_id BIGINT NOT NULL, enrollment_id BIGINT NOT NULL, submission_type VARCHAR(20) NOT NULL,
                content VARCHAR(10000) NOT NULL, submitted_at TIMESTAMP NOT NULL, submission_count INT NOT NULL,
                score DECIMAL(5,2), passed BOOLEAN, feedback VARCHAR(10000), graded_at TIMESTAMP,
                graded_by_member_id BIGINT, version BIGINT NOT NULL,
                created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL,
                CONSTRAINT uk_assignment_submissions_assignment_enrollment UNIQUE(assignment_id,enrollment_id))
            """);
        jdbc.update("DELETE FROM assignment_submissions");
        jdbc.update("DELETE FROM assignments");
        jdbc.update("INSERT INTO assignments VALUES (20,1,'required',null,true,DATE '2026-09-27',80,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
        jdbc.update("INSERT INTO assignments VALUES (21,1,'optional',null,false,DATE '2026-09-27',80,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
        jdbc.update("INSERT INTO assignments VALUES (22,2,'other course',null,true,DATE '2026-09-27',80,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
    }
    @Test void actualQueriesDistinguishMissingPendingFailedAndPassedAndIgnoreOptional() {
        assertThat(submissions.hasUnsatisfiedRequired(1L,10L)).isTrue();
        assertThat(submissions.hasMissingOrFailedRequired(1L,10L)).isTrue();
        assertThat(submissions.hasPendingRequired(1L,10L)).isFalse();
        insert(20,10);
        assertThat(submissions.hasUnsatisfiedRequired(1L,10L)).isTrue();
        assertThat(submissions.hasMissingOrFailedRequired(1L,10L)).isFalse();
        assertThat(submissions.hasPendingRequired(1L,10L)).isTrue();
        jdbc.update("UPDATE assignment_submissions SET graded_at=CURRENT_TIMESTAMP, score=79, passed=false, graded_by_member_id=3");
        assertThat(submissions.hasMissingOrFailedRequired(1L,10L)).isTrue();
        assertThat(submissions.hasPendingRequired(1L,10L)).isFalse();
        jdbc.update("UPDATE assignment_submissions SET score=80, passed=true");
        assertThat(submissions.hasUnsatisfiedRequired(1L,10L)).isFalse();
        assertThat(submissions.hasUnsatisfiedRequired(2L,10L)).isTrue();
        assertThat(submissions.hasUnsatisfiedRequired(1L,11L)).isTrue();
        assertThat(submissions.hasUnsatisfiedRequired(999L,10L)).isFalse();
        insert(21,10);
        assertThat(submissions.hasUnsatisfiedRequired(1L,10L)).isFalse();
        assertThat(submissions.hasPendingRequired(1L,10L)).isFalse();
    }
    @Test void onePassedRequiredDoesNotHideAnotherMissingRequired() {
        jdbc.update("UPDATE assignments SET is_required=true WHERE id=21");
        insert(20,10);
        jdbc.update("UPDATE assignment_submissions SET graded_at=CURRENT_TIMESTAMP, score=80, passed=true, graded_by_member_id=3");
        assertThat(submissions.hasUnsatisfiedRequired(1L,10L)).isTrue();
        assertThat(submissions.hasMissingOrFailedRequired(1L,10L)).isTrue();
    }
    @Test void actualDateAndUniqueQueriesRespectBoundaries() {
        assertThat(assignments.existsByCourseIdAndIsRequiredTrueAndDueDateBefore(1L,DUE)).isFalse();
        assertThat(assignments.existsByCourseIdAndIsRequiredTrueAndDueDateBefore(1L,DUE.plusDays(1))).isTrue();
        assertThat(assignments.hasOutsidePeriod(1L,DUE,DUE)).isFalse();
        assertThat(assignments.hasOutsidePeriod(1L,DUE,DUE.minusDays(1))).isTrue();
        insert(20,10);
        assertThatThrownBy(() -> insert(20,10)).isInstanceOf(org.springframework.dao.DataIntegrityViolationException.class);
    }
    @Test void optimisticVersionRejectsStaleSubmissionContent() throws Exception {
        // 두 EntityManager의 독립 트랜잭션에서 같은 버전을 읽고 덮어쓰는 경쟁을 재현한다.
        long assignmentId = 999, enrollmentId = 999;
        try(var connection = jdbc.getDataSource().getConnection()) {
            connection.setAutoCommit(true);
            try(var st=connection.createStatement()) {
                st.executeUpdate("INSERT INTO assignments VALUES (999,999,'concurrent',null,true,DATE '2026-09-27',80,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");
            }
        }
        EntityManager first = emf.createEntityManager(), second = emf.createEntityManager();
        Long id = null;
        try {
            first.getTransaction().begin();
            var row = AssignmentSubmission.create(first.getReference(Assignment.class,assignmentId),
                first.getReference(Enrollment.class,enrollmentId),AssignmentSubmissionType.TEXT,"initial",NOW);
            first.persist(row); first.getTransaction().commit(); id=row.getId(); first.clear();
            first.getTransaction().begin(); second.getTransaction().begin();
            var a=first.find(AssignmentSubmission.class,id);
            var b=second.find(AssignmentSubmission.class,id);
            a.resubmit(AssignmentSubmissionType.TEXT,"first",NOW.plusSeconds(1));
            first.getTransaction().commit();
            b.resubmit(AssignmentSubmissionType.TEXT,"stale",NOW.plusSeconds(2));
            assertThatThrownBy(() -> second.getTransaction().commit()).isInstanceOf(RollbackException.class);
            first.clear();
            assertThat(first.find(AssignmentSubmission.class,id).getContent()).isEqualTo("first");
            assertThat(first.find(AssignmentSubmission.class,id).getVersion()).isEqualTo(1);
        } finally {
            if(first.getTransaction().isActive()) first.getTransaction().rollback();
            if(second.getTransaction().isActive()) second.getTransaction().rollback();
            first.close(); second.close();
            try(var connection=jdbc.getDataSource().getConnection();var st=connection.createStatement()) {
                connection.setAutoCommit(true);
                st.executeUpdate("DELETE FROM assignment_submissions WHERE assignment_id=999");
                st.executeUpdate("DELETE FROM assignments WHERE id=999");
            }
        }
    }
    private void insert(long assignment,long enrollment) {
        jdbc.update("""
            INSERT INTO assignment_submissions(assignment_id,enrollment_id,submission_type,content,submitted_at,
                submission_count,version,created_at,updated_at)
            VALUES (?,?,'TEXT','answer',CURRENT_TIMESTAMP,1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
            """,assignment,enrollment);
    }
}
