package com.be.certificate;

import com.be.certificate.controller.CertificateController;
import com.be.certificate.dto.CertificateResponse;
import com.be.certificate.repository.CertificateRepository;
import com.be.certificate.service.*;
import com.be.global.exception.BusinessException;
import com.be.global.exception.ErrorCode;
import com.be.security.JwtTestSupport;
import java.time.Clock;
import java.util.ArrayList;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.data.jpa.test.autoconfigure.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.annotation.DirtiesContext;
import org.springframework.test.context.*;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;
import static com.be.certificate.CertificateFixtures.*;
import static org.assertj.core.api.Assertions.*;
import static org.mockito.Mockito.*;

// 실제 JPA/트랜잭션/행 잠금으로 검증. 운영 DB 및 기존 데이터에는 접근하지 않는다.
@DataJpaTest(properties = {"spring.jpa.hibernate.ddl-auto=none", "spring.jpa.show-sql=false", "spring.sql.init.mode=never"})
@Import(CertificateService.class)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class CertificatePersistenceTest {
    @Autowired CertificateService service;
    @Autowired CertificateRepository certificates;
    @Autowired JdbcTemplate jdbc;
    @MockitoBean Clock clock;

    @DynamicPropertySource static void properties(DynamicPropertyRegistry r) {
        r.add("jwt.secret", JwtTestSupport::secret);
        r.add("jwt.access-token-ttl-seconds", () -> 300);
        r.add("jwt.refresh-token-ttl-seconds", () -> 3600);
    }

    @BeforeEach void schema() {
        when(clock.instant()).thenReturn(CLOCK.instant());
        jdbc.execute("CREATE TABLE courses(id BIGINT PRIMARY KEY,retraining_policy_id BIGINT,occurrence_number INT,title VARCHAR(200),description TEXT,course_type VARCHAR(20),status VARCHAR(20),start_date DATE,end_date DATE,passing_progress_rate DECIMAL(5,2),instructor_id BIGINT,created_at TIMESTAMP,updated_at TIMESTAMP)");
        jdbc.execute("CREATE TABLE members(id BIGINT PRIMARY KEY,employee_number VARCHAR(50),email VARCHAR(255),password_hash VARCHAR(255),name VARCHAR(100),department_id BIGINT,job_position_id BIGINT,status VARCHAR(20),hire_date DATE,resigned_at TIMESTAMP,created_at TIMESTAMP,updated_at TIMESTAMP)");
        jdbc.execute("CREATE TABLE assignment_rules(id BIGINT PRIMARY KEY,course_id BIGINT,department_id BIGINT,job_position_id BIGINT,rule_type VARCHAR(30),new_employee_days SMALLINT,is_active BOOLEAN,created_at TIMESTAMP,updated_at TIMESTAMP)");
        jdbc.execute("CREATE TABLE enrollments(id BIGINT PRIMARY KEY,member_id BIGINT,course_id BIGINT,status VARCHAR(20),assignment_source VARCHAR(20),assignment_rule_id BIGINT,assigned_at TIMESTAMP,started_at TIMESTAMP,completed_at TIMESTAMP,due_date DATE,version BIGINT,created_at TIMESTAMP,updated_at TIMESTAMP)");
        jdbc.execute("""
                CREATE TABLE certificates(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                enrollment_id BIGINT NOT NULL, certificate_number VARCHAR(64) NOT NULL,
                issued_at TIMESTAMP(6) NOT NULL, member_name VARCHAR(100) NOT NULL,
                course_title VARCHAR(200) NOT NULL, completed_at TIMESTAMP(6) NOT NULL,
                CONSTRAINT uk_certificates_enrollment UNIQUE(enrollment_id),
                CONSTRAINT uk_certificates_number UNIQUE(certificate_number),
                CONSTRAINT fk_certificates_enrollment FOREIGN KEY(enrollment_id) REFERENCES enrollments(id),
                CONSTRAINT chk_certificates_dates CHECK(issued_at >= completed_at))
                """);
        jdbc.update("INSERT INTO courses(id,title,course_type,status,passing_progress_rate) VALUES(1,'과정','MANDATORY','OPEN',100)");
        jdbc.update("INSERT INTO members(id,name,status) VALUES(2,'직원','ACTIVE')");
        jdbc.update("INSERT INTO enrollments(id,member_id,course_id,status,assignment_source,assigned_at,started_at,completed_at,due_date,version) VALUES(3,2,1,'COMPLETED','MANUAL',TIMESTAMP '2026-09-19 01:00:00',TIMESTAMP '2026-09-20 01:00:00',TIMESTAMP '2026-09-20 16:30:00',DATE '2026-10-31',0)");
    }

    @AfterEach void cleanup() {
        jdbc.execute("DROP TABLE certificates");
        jdbc.execute("DROP TABLE enrollments");
        jdbc.execute("DROP TABLE assignment_rules");
        jdbc.execute("DROP TABLE members");
        jdbc.execute("DROP TABLE courses");
    }

    @Test void simultaneousFirstRequestsCreateExactlyOneAndDoNotMutateEnrollment() throws Exception {
        var before = jdbc.queryForMap("SELECT * FROM enrollments WHERE id=3");
        int requests = 6;
        var barrier = new CyclicBarrier(requests);
        var executor = Executors.newFixedThreadPool(requests);
        var futures = new ArrayList<Future<CertificateService.IssueResult>>();
        try {
            for (int i = 0; i < requests; i++) futures.add(executor.submit(() -> {
                barrier.await(10, TimeUnit.SECONDS);
                return service.issue(3L, OWNER);
            }));
            var results = new ArrayList<CertificateService.IssueResult>();
            for (var future : futures) results.add(future.get(20, TimeUnit.SECONDS));
            assertThat(results.stream().filter(CertificateService.IssueResult::created)).hasSize(1);
            assertThat(results.stream().map(CertificateService.IssueResult::certificate).distinct()).hasSize(1);
            assertThat(certificates.count()).isEqualTo(1);
            assertThat(jdbc.queryForMap("SELECT * FROM enrollments WHERE id=3")).isEqualTo(before);
        } finally {
            executor.shutdownNow();
            assertThat(executor.awaitTermination(10, TimeUnit.SECONDS)).isTrue();
        }
    }

    @Test void committedSnapshotSurvivesProfileChangesPdfFailureAndRedownload() {
        var issued = service.issue(3L, OWNER).certificate();
        jdbc.update("UPDATE members SET name='새 이름' WHERE id=2");
        jdbc.update("UPDATE courses SET title='새 과정' WHERE id=1");
        assertThat(service.issue(3L, ADMIN).certificate()).isEqualTo(issued);
        assertThat(service.get(3L, OWNER)).isEqualTo(issued);
        var before = jdbc.queryForMap("SELECT * FROM enrollments WHERE id=3");
        var failedRenderer = mock(CertificatePdfRenderer.class);
        when(failedRenderer.render(any())).thenThrow(new BusinessException(ErrorCode.CERTIFICATE_PDF_GENERATION_FAILED));
        var controller = new CertificateController(service, failedRenderer);
        assertThatThrownBy(() -> controller.download(3L, OWNER)).isInstanceOf(BusinessException.class);
        assertThat(service.get(3L, OWNER)).isEqualTo(issued);
        assertThat(certificates.count()).isEqualTo(1);
        assertThat(jdbc.queryForMap("SELECT * FROM enrollments WHERE id=3")).isEqualTo(before);
        assertThat(new CertificateController(service, new CertificatePdfRenderer()).download(3L, OWNER).getBody())
                .isNotEmpty();
    }

    @Test void databaseUniqueConstraintsProtectEnrollmentAndNumber() {
        CertificateResponse issued = service.issue(3L, OWNER).certificate();
        String insert = "INSERT INTO certificates(enrollment_id,certificate_number,issued_at,member_name,course_title,completed_at) VALUES(?,?,CURRENT_TIMESTAMP,'직원','과정',TIMESTAMP '2026-09-20 16:30:00')";
        assertThatThrownBy(() -> jdbc.update(insert, 3, "another-number")).isInstanceOf(DataIntegrityViolationException.class);
        jdbc.update("INSERT INTO enrollments(id,version) VALUES(4,0)");
        assertThatThrownBy(() -> jdbc.update(insert, 4, issued.certificateNumber())).isInstanceOf(DataIntegrityViolationException.class);
        assertThat(certificates.count()).isEqualTo(1);
    }
}
